# Generated by Django 3.2.9 on 2021-11-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restauran_ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Restauran_ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restauran_ubicacion')),
            ],
        ),
    ]
